common: &common
  username: <%= `whoami`.strip %>
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  database: rigel_development
  <<: *common
test:
  database: rigel_test
  username: <%= `whoami`.strip %>
  adapter: postgresql
  pool: 5
  timeout: 5000
staging:
  database: rigel_staging
  <<: *common
production:
  database: rigel_production
  <<: *common
